name: Tosell
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  intl: 0.20.2 
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  input_quantity: ^2.5.0
  shared_preferences: ^2.5.2
  go_router: ^14.8.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  provider: ^6.1.2
  state_notifier: ^1.0.0
  dio: ^5.8.0+1
  another_stepper: ^1.2.2
  google_maps_flutter: ^2.10.1
  pull_to_refresh_flutter3: ^2.0.2
  hooks_riverpod: ^2.6.1
  easy_localization: ^3.0.7
  month_picker_dialog: ^6.0.3
  fluttertoast: ^8.2.12
  simple_barcode_scanner: ^0.3.0
  infinite_scroll_pagination: ^4.0.0
  fl_chart: ^1.0.0
  geolocator: ^14.0.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dropdown_search: ^5.0.6
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lang/
    - assets/svg/
    - assets/animations/
    - assets/fonts/Tajawal-Regular.ttf
    - assets/fonts/Tajawal-Bold.ttf
    - assets/fonts/Tajawal-Light.ttf
    - assets/fonts/Tajawal-Medium.ttf
    - assets/fonts/Tajawal-Black.ttf


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300